# terminal.shell = "wsl -d archlinux --cd ~"
[terminal.shell]
program = "wsl -d archlinux --cd ~"

[window]
startup_mode = "Fullscreen"
decorations = "none"
padding = { x = 0, y = 0 }
dynamic_padding = true
dynamic_title = true
opacity = 1

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[general]
import = [
  "C:\\Users\\PedroNieuwenhoff\\AppData\\Roaming\\alacritty\\./themes/themes/blood_moon.toml"
]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
